FROM n8nio/n8n:latest

USER root

# Set working directory
WORKDIR /home/node/.n8n

# Set timezone
ENV GENERIC_TIMEZONE=Asia/Kolkata
ENV TZ=Asia/Kolkata

USER node

# Expose port
EXPOSE 5678

# Run n8n directly (it's already an executable)
CMD ["n8n"]